name: Run Virtual Machine Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip and pytest
        run: |
          python -m ensurepip --upgrade
          pip install --upgrade pip
          pip install pytest

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping pip install."
          fi

      - name: Check installed packages
        run: |
          pip list  # To verify if pytest and other dependencies are installed

      - name: Run tests with pytest (verbose)
        run: |
          pytest -v  # Run pytest with verbose logging to capture more details

      - name: Deploy to VM (optional)
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H server.com >> ~/.ssh/known_hosts
          ssh user@server "bash deploy.sh"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clean up
        run: |
          echo "Cleaning up after deployment..."
